### ISSUE TITLE
Support for OpenSSH ecdsa-sk & ed25519-sk

### ISSUE THREAD

**Issue by Utesgui** [Keeper-Security/Commander#1280]
I would love to use my ed25519-sk-keys with the keeper ssh command.

Support was added to cryptography in March:
https://github.com/pyca/cryptography/issues/10604
![image](https://github.com/user-attachments/assets/8f28cc50-e506-44c0-af61-335d002c2e2d)

**Comment by sk-keeper** [comment]
The mentioned `cryptography` thread is about public not private key.
The latest `cryptography` package `43.0.0` cannot load Yubikey's private key.
```
>>> serialization.load_ssh_private_key(private_key.encode(), password=b'...')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/skolupaev/Work/PY/sdk/lib/python3.11/site-packages/cryptography/hazmat/primitives/serialization/ssh.py", line 696, in load_ssh_private_key
    pubfields, pubdata = kformat.get_public(pubdata)
                         ^^^^^^^^^^^^^^^^^^
AttributeError: '_SSHFormatSKEd25519' object has no attribute 'get_public'. Did you mean: 'load_public'?
```
