### ISSUE TITLE
Cryptodome - ValueError: MAC check failed 

### ISSUE THREAD

**Issue by t1hom7as** [Keeper-Security/Commander#173]
When connecting to our keeper instance there is a ValueError thrown, it seems this is from the python package `Cryptodome`. I am trying to login using the following params:
`keeper --server keeper.mydomain.com --user myusername --password mypassword --debug shell` 

Here is the full trace:
```  _  __  
 | |/ /___ ___ _ __  ___ _ _ 
 | ' </ -_) -_) '_ \/ -_) '_|
 |_|\_\___\___| .__/\___|_|
              |_|            

 password manager & digital vault


Logging in...
Traceback (most recent call last):
  File "/usr/local/bin/keeper", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/keepercommander/__main__.py", line 158, in main
    cli.loop(params)
  File "/usr/local/lib/python3.7/site-packages/keepercommander/cli.py", line 203, in loop
    login(params)
  File "/usr/local/lib/python3.7/site-packages/keepercommander/api.py", line 89, in login
    pre_login_rs = rest_api.pre_login(params.rest_context, params.user)
  File "/usr/local/lib/python3.7/site-packages/keepercommander/rest_api.py", line 190, in pre_login
    rq.authRequest.encryptedDeviceToken = get_device_token(context)
  File "/usr/local/lib/python3.7/site-packages/keepercommander/rest_api.py", line 169, in get_device_token
    rs = execute_rest(context, 'authentication/get_device_token', rq.SerializeToString())
  File "/usr/local/lib/python3.7/site-packages/keepercommander/rest_api.py", line 144, in execute_rest
    return decrypt_aes(rs.content, context.transmission_key)
  File "/usr/local/lib/python3.7/site-packages/keepercommander/rest_api.py", line 100, in decrypt_aes
    return cipher.decrypt_and_verify(data[12:-16], data[-16:])
  File "/usr/local/lib/python3.7/site-packages/Cryptodome/Cipher/_mode_gcm.py", line 567, in decrypt_and_verify
    self.verify(received_mac_tag)
  File "/usr/local/lib/python3.7/site-packages/Cryptodome/Cipher/_mode_gcm.py", line 508, in verify
    raise ValueError("MAC check failed")
ValueError: MAC check failed```

**Comment by sk-keeper** [comment]
--server option describes Keeper server. Valid values are keepersecurity.com and keepersecurity.eu. This parameter can be omitted from the command line.
`keeper --user myusername shell`
