### ISSUE TITLE
Keeper fails on Python 3.5

### ISSUE THREAD

**Issue by jeremywiebe** [Keeper-Security/Commander#265]
The Pypi page specifies that Keeper 4.35 (latest as of this writing) requires Python 3.4 or later. However, when I try to run it on Python 3.5, it raises a `SyntaxError` due to type annotations in a dependency.

The stack trace is as follows:
```
Traceback (most recent call last):
  File "/usr/local/bin/keeper", line 7, in <module>
    from keepercommander.__main__ import main
  File "/usr/local/lib/python3.5/dist-packages/keepercommander/__main__.py", line 26, in <module>
    from . import cli
  File "/usr/local/lib/python3.5/dist-packages/keepercommander/cli.py", line 23, in <module>
    from prompt_toolkit import PromptSession
  File "/usr/local/lib/python3.5/dist-packages/prompt_toolkit/__init__.py", line 16, in <module>
    from .application import Application
  File "/usr/local/lib/python3.5/dist-packages/prompt_toolkit/application/__init__.py", line 1, in <module>
    from .application import Application
  File "/usr/local/lib/python3.5/dist-packages/prompt_toolkit/application/application.py", line 245
    self.full_screen: bool = full_screen
                    ^
SyntaxError: invalid syntax
```

**Comment by sk-keeper** [comment]
This exception is raised in the dependency project [prompt_toolkit](https://pypi.org/project/prompt-toolkit/).
The latest version of this project (3.0.5) requires Python version >= 3,6,1
Downgrading prompt_toolkit to 2.x may fix this issue.
`pip install prompt-toolkit==2.0.10`

**Comment by jeremywiebe** [comment]
That worked! :) Thank-you.

**Comment by sndrr** [comment]
So this issue can be closed @jeremywiebe ?

**Comment by jeremywiebe** [comment]
In as far as the workaround that @sk-keeper provided yes. 

The [Pypi page](https://pypi.org/project/keepercommander/) is still incorrect in specifying that Keeper runs on Python 3.4 and above, but I don't know how the project tracks that. Thanks for checking back. 

<img width="195" alt="image" src="https://user-images.githubusercontent.com/77138/92264496-2a917380-ee93-11ea-95ad-da67a07a79fb.png">

**Comment by sk-keeper** [comment]
The fix has not been published to PyPi yet.

**Comment by OmarTapps** [comment]
I was trying the latest Keeper Commander today, v 4.87, and this issue still happens, but on a different place.

I'm running python 3.5 as well, and prompt_toolkit is on the expected 2.0.10 version. The error now seems to be on keeper itself, not on a dependency:

```
$ keeper --help
Traceback (most recent call last):
  File "c:\programming\python\python35\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\programming\python\python35\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Programming\Python\Python35\Scripts\keeper.exe\__main__.py", line 4, in <module>
  File "c:\programming\python\python35\lib\site-packages\keepercommander\__main__.py", line 27, in <module>
    from . import cli
  File "c:\programming\python\python35\lib\site-packages\keepercommander\cli.py", line 28, in <module>
    from .commands.msp import get_mc_by_name_or_id
  File "c:\programming\python\python35\lib\site-packages\keepercommander\commands\msp.py", line 18, in <module>
    from .enterprise import EnterpriseCommand
  File "c:\programming\python\python35\lib\site-packages\keepercommander\commands\enterprise.py", line 40, in <module>
    from .record import RecordAddCommand
  File "c:\programming\python\python35\lib\site-packages\keepercommander\commands\record.py", line 28, in <module>
    from .. import api, display, generator
  File "c:\programming\python\python35\lib\site-packages\keepercommander\api.py", line 23, in <module>
    from . import rest_api, APIRequest_pb2 as proto, loginv3
  File "c:\programming\python\python35\lib\site-packages\keepercommander\loginv3.py", line 325
    selection: str = input('Type your selection: ')
             ^
SyntaxError: invalid syntax
```

For now my workaround to this is downgrading keeper. I installed 4.35 and it seems to be working.

**Comment by sk-keeper** [comment]
Yes, you are right.
This code introduced the Python's Type Annotation which was added to Python 3.6
There was no need for adding types and breaking compatibility with the Python 3.5
