### ISSUE TITLE
Upgrading from 4.36 to 4.61 breaks my code

### ISSUE THREAD

**Issue by alainbodiguel** [Keeper-Security/Commander#320]
We are importing the commander library in our application in order to interact with our vault.  
While upgrading from 4.36 to 4.61 we get an error. Is there a changelog or upgrading guide that could help us identify what changed?

```
Traceback (most recent call last):
  File "testkeeper.py", line 1, in <module>
    from mymodule import keeper
  File "/home/alain/IdeaProjects/myproject/mymodule/mymodule/keeper.py", line 1, in <module>
    from keepercommander.commands.folder import FolderMakeCommand, FolderLinkCommand
  File "/home/alain/IdeaProjects/myproject/venv/lib/python3.8/site-packages/keepercommander/commands/folder.py", line 22, in <module>
    from .. import api, display
  File "/home/alain/IdeaProjects/myproject/venv/lib/python3.8/site-packages/keepercommander/api.py", line 23, in <module>
    from . import rest_api, APIRequest_pb2 as proto, loginv3
  File "/home/alain/IdeaProjects/myproject/venv/lib/python3.8/site-packages/keepercommander/loginv3.py", line 23, in <module>
    from . import cli
  File "/home/alain/IdeaProjects/myproject/venv/lib/python3.8/site-packages/keepercommander/cli.py", line 35, in <module>
    from .autocomplete import CommandCompleter
  File "/home/alain/IdeaProjects/myproject/venv/lib/python3.8/site-packages/keepercommander/autocomplete.py", line 19, in <module>
    from .commands.folder import mv_parser
ImportError: cannot import name 'mv_parser' from partially initialized module 'keepercommander.commands.folder' (most likely due to a circular import) (/home/alain/IdeaProjects/myproject/venv/lib/python3.8/site-packages/keepercommander/commands/folder.py)
```

**Comment by alainbodiguel** [comment]
Fixed by moving around imports.

**Comment by maksimu** [comment]
Hi @alainbodiguel,

Version 4.61 compare to 4.36 has pretty significant changes, especially Login V3. We are glad that your code is working now.

**Comment by alainbodiguel** [comment]
Changing the order of the imports and disabling login V3 made it for me. I still need to test all my use case, but a changelog/upgrading guide would be useful for those who rely on your API for their application.
