### ISSUE TITLE
failed to add a new record to the folder shared in keeper with python. error FileNotFoundError: [Errno 2] No such file or directory: '' when logging in

### ISSUE THREAD

**Issue by giovannabarbosamg** [Keeper-Security/Commander#348]
I'm trying to execute the command in python said in the custom folder (Commander/keepercommander/custom/add_record_to_shared_folder.py), apparently the login part ends up leading to an error. if you can help me:
`Traceback (most recent call last):
File "/home/user/PycharmProjects/project/test.py", line 13, in <module>
    api.sync_down(params)
File "/home/user/.local/lib/python3.8/site-packages/keepercommander/api.py", line 431, in sync_down
    response_json = communicate(params, rq)
File "/home/user/.local/lib/python3.8/site-packages/keepercommander/api.py", line 1355, in communicate
    login(params)
File "/home/user/.local/lib/python3.8/site-packages/keepercommander/api.py", line 81, in login
    loginv3.LoginV3Flow.login(params)
File "/home/user/.local/lib/python3.8/site-packages/keepercommander/loginv3.py", line 41, in login
    CommonHelperMethods.startup_check(params)
File "/home/user/.local/lib/python3.8/site-packages/keepercommander/loginv3.py", line 1095, in startup_check
    with io.open(params.config_filename, 'w') as config_file:
FileNotFoundError: [Errno 2] No such file or directory: ''`

**Comment by maksimu** [comment]
I have made new sample and made a Pull Request. In the mean time, you can see the sample code [HERE](https://github.com/Keeper-Security/Commander/blob/b527f146421b9886a2567c64c991bb5b26bbe09e/keepercommander/custom/add_record_to_shared_folder.py)

**Comment by maksimu** [comment]
Updated sample was merged into the master branch

**Comment by giovannabarbosamg** [comment]
hey @maksimuhey, how do i run this record addition without having my credentials (email and password) exposed? like for example with api key or something
