### ISSUE TITLE
An unexpected error occurred: X962. Toggle debug to print traceback

### ISSUE THREAD

**Issue by karezza** [Keeper-Security/Commander#358]
Installed today & no luck ...

See below for OS & python version.

`$ keeper login t@domain.com
An unexpected error occurred: X962. Toggle debug to print traceback
Not logged in> debug
Debug ON
Not logged in> login t@domain.com
Logging in to Keeper Commander
Login v3 Start as 't@domain.com'
Configuration file 'config.json' exists and is readable
X962
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/keepercommander/cli.py", line 490, in loop
    result = do_command(params, command)
  File "/usr/local/lib/python3.6/site-packages/keepercommander/cli.py", line 330, in do_command
    result = command.execute_args(params, args, command=orig_cmd)
  File "/usr/local/lib/python3.6/site-packages/keepercommander/commands/base.py", line 212, in execute_args
    return self.execute(params, **d)
  File "/usr/local/lib/python3.6/site-packages/keepercommander/commands/utils.py", line 449, in execute
    api.login(params)
  File "/usr/local/lib/python3.6/site-packages/keepercommander/api.py", line 81, in login
    loginv3.LoginV3Flow.login(params)
  File "/usr/local/lib/python3.6/site-packages/keepercommander/loginv3.py", line 48, in login
    encryptedDeviceToken = LoginV3API.get_device_id(params)
  File "/usr/local/lib/python3.6/site-packages/keepercommander/loginv3.py", line 551, in get_device_id
    public_key = CommonHelperMethods.public_key_ecc(params)
  File "/usr/local/lib/python3.6/site-packages/keepercommander/loginv3.py", line 1060, in public_key_ecc
    pub_key_bytes = pub_key.public_bytes(serialization.Encoding.X962, serialization.PublicFormat.UncompressedPoint)
  File "/usr/lib64/python3.6/enum.py", line 326, in __getattr__
    raise AttributeError(name) from None
AttributeError: X962
An unexpected error occurred: X962. Toggle debug to print traceback
Not logged in>
Goodbye.

[/home/t]
t@ansible $ cat /etc/redhat-release
CentOS Linux release 8.3.2011
[/home/t]
t@ansible $ python3
python3                   python3.6-config          python3.6m-config         python3-config
python3.6                 python3.6m                python3.6m-x86_64-config`

**Comment by maksimu** [comment]
Looks like you have older version of `cryptography` package installed. Try to run following command to upgrade it:

```
python -m pip install -U cryptography
```

**Comment by karezza** [comment]
That fixed it, thank you!
