### ISSUE TITLE
ModuleNotFoundError: No module named 'keepercommander.commands.helpers'

### ISSUE THREAD

**Issue by groner** [Keeper-Security/Commander#470]
Keeper doesn't run after upgrading to 16.1.9
```
: kai@dipper kai; keeper shell
Traceback (most recent call last):
  File "/home/kai/.local/bin/keeper", line 5, in <module>
    from keepercommander.__main__ import main
  File "/home/kai/.local/opt/keepercommander/lib/python3.9/site-packages/keepercommander/__main__.py", line 27, in <module>
    from . import cli
  File "/home/kai/.local/opt/keepercommander/lib/python3.9/site-packages/keepercommander/cli.py", line 37, in <module>
    from .autocomplete import CommandCompleter
  File "/home/kai/.local/opt/keepercommander/lib/python3.9/site-packages/keepercommander/autocomplete.py", line 20, in <module>
    from .commands.utils import ConnectCommand
  File "/home/kai/.local/opt/keepercommander/lib/python3.9/site-packages/keepercommander/commands/utils.py", line 50, in <module>
    from .helpers.timeout import (
ModuleNotFoundError: No module named 'keepercommander.commands.helpers'
```

**Comment by maksimu** [comment]
Thank you for reporting this issue to us. We fixed it in the new version 16.1.10
