### ISSUE TITLE
keeper export not working since "Thursday, March 2, 2022"

### ISSUE THREAD

**Issue by flybyray** [Keeper-Security/Commander#696]
Error:

```txt
Processing... please wait.
An unexpected error occurred: 'NoneType' object is not iterable. Toggle debug to print traceback
```

We receive that from an automated backup which worked at least 2 month until 2 March 2022.
On our side is no change hence the keeper servers changed something.

I can even reproduce this error on a newly setup client device with `keeper shell`.

```shell
My Vault> export --format keepass --keepass-file-password 'pasword' --force backup
Processing... please wait.
An unexpected error occurred: 'NoneType' object is not iterable. Toggle debug to print traceback
```

I tried to export with different format `json`  and `csv`. result is the same.

DEBUG Trace

```txt
'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/robert.rettig/git/github.com/Keeper-Security/Commander/keepercommander/cli.py", line 547, in loop
    result = do_command(params, command)
  File "/home/robert.rettig/git/github.com/Keeper-Security/Commander/keepercommander/cli.py", line 369, in do_command
    result = command.execute_args(params, args, command=orig_cmd)
  File "/home/robert.rettig/git/github.com/Keeper-Security/Commander/keepercommander/importer/commands.py", line 139, in execute_args
    Command.execute_args(self, params, args, **kwargs)
  File "/home/robert.rettig/git/github.com/Keeper-Security/Commander/keepercommander/commands/base.py", line 303, in execute_args
    return self.execute(params, **d)
  File "/home/robert.rettig/git/github.com/Keeper-Security/Commander/keepercommander/importer/commands.py", line 252, in execute
    imp_exp.export(params, export_format, export_name, **kwargs)
  File "/home/robert.rettig/git/github.com/Keeper-Security/Commander/keepercommander/importer/imp_exp.py", line 338, in export
    rec = convert_keeper_record(record, exporter.has_attachments())
  File "/home/robert.rettig/git/github.com/Keeper-Security/Commander/keepercommander/importer/imp_exp.py", line 211, in convert_keeper_record
    for custom in data['custom']:
TypeError: 'NoneType' object is not iterable
An unexpected error occurred: 'NoneType' object is not iterable. Toggle debug to print traceback
```

**Comment by flybyray** [comment]
Is there a way to determine which record might be corrupt? Maybe via the WebConsole?

**Comment by sk-keeper** [comment]
added to release 16.5.14
