### ISSUE TITLE
No such file or directory file://pipe/openssh-ssh-agent (Windows, Powershell 7, Commander CLI)

### ISSUE THREAD

**Issue by TBSJordanNash** [Keeper-Security/Commander#723]
1. I created an ssh pair using the integrated ssh-keygen on Windows with default settings. I pasted the entirety of the private file into Keeper, including the -----BEGIN OPENSSH PRIVATE KEY----- header and footer. 
2. I exported the public version into the target server using scp into ~/.ssh/authorized_keys.
3. I installed the Commander CLI onto the local computer and logged in.
5. ssh shows the record
6. 
    C:\Users\username>keeper-commander.exe ssh
      #  Record UID              Type     Title                      Description
    ---  ----------------------  -------  -------------------------  ----------------------
      1  DFB*******************  sshKeys  myserver                  username @ myserver:22
7. When I attempt to ssh into it (ssh GUID), it fails:
    My Vault> ssh DFB*****************
	    [Errno 2] No such file or directory: '[\\\\.\\pipe\\openssh-ssh-agent](file://pipe/openssh-ssh-agent)'
	    Traceback (most recent call last):
	      File "keepercommander\cli.py", line 547, in loop
	      File "keepercommander\cli.py", line 369, in do_command
	      File "keepercommander\commands\base.py", line 307, in execute_args
	      File "keepercommander\commands\connect.py", line 351, in execute
	      File "keepercommander\commands\connect.py", line 240, in add_ssh_key
	      File "keepercommander\commands\connect.py", line 106, in __enter__
	    FileNotFoundError: [Errno 2] No such file or directory: '[\\\\.\\pipe\\openssh-ssh-agent](file://pipe/openssh-ssh-agent)'
	    An unexpected error occurred: [Errno 2] No such file or directory: '[\\\\.\\pipe\\openssh-ssh-agent](file://pipe/openssh-ssh-agent)'. Toggle debug to print traceback
8. If I change the record type to server, it succeeds, but uses password login.

**Comment by TBSJordanNash** [comment]
My intent is to get Commander to work so that I can integrate it into VSCode for interactive sessions without storing the key locally.

**Comment by TBSJordanNash** [comment]
> `ssh-agent` is a Windows service that needs to be running. The service name is `ssh-agent` Display name `OpenSSH Authentication Agent`

That was the fix action. Thanks!
