### ISSUE TITLE
TypeError: Descriptors cannot not be created directly.

### ISSUE THREAD

**Issue by PiotrBaran1010** [Keeper-Security/Commander#777]
After installing most recent keeper commander version with pip, running any command gives the following error:
`Traceback (most recent call last):
  File "C:\Python3\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python3\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Python3\Scripts\keeper.exe\__main__.py", line 4, in <module>
  File "C:\Python3\lib\site-packages\keepercommander\__main__.py", line 26, in <module>
    from . import cli
  File "C:\Python3\lib\site-packages\keepercommander\cli.py", line 28, in <module>
    from .commands.msp import get_mc_by_name_or_id
  File "C:\Python3\lib\site-packages\keepercommander\commands\msp.py", line 18, in <module>
    from .enterprise import EnterpriseCommand
  File "C:\Python3\lib\site-packages\keepercommander\commands\enterprise.py", line 39, in <module>
    from .record import RecordAddCommand
  File "C:\Python3\lib\site-packages\keepercommander\commands\record.py", line 26, in <module>
    from .. import api, display, generator
  File "C:\Python3\lib\site-packages\keepercommander\api.py", line 23, in <module>
    from . import rest_api, APIRequest_pb2 as proto, loginv3
  File "C:\Python3\lib\site-packages\keepercommander\rest_api.py", line 22, in <module>
    from . import APIRequest_pb2 as proto
  File "C:\Python3\lib\site-packages\keepercommander\APIRequest_pb2.py", line 12, in <module>
    from .commands import enterprise_pb2 as enterprise__pb2
  File "C:\Python3\lib\site-packages\keepercommander\commands\enterprise_pb2.py", line 33, in <module>
    _descriptor.EnumValueDescriptor(
  File "C:\Python3\lib\site-packages\google\protobuf\descriptor.py", line 755, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates`

Downgrading protobuf to <=3.20.1 after the installation seems to fix the issue temporarily

**Comment by kihneman** [comment]
@PiotrBaran1010, could you share the Python packages you have installed by executing `pip list`? We also need to know the version of Commander that you are using which is found by executing `keeper --version` and the version of Python by executing `python -V`.

**Comment by maksimu** [comment]
@PiotrBaran1010 it looks like you have an old version of commander (based on the file structure in stacktrace). Latest version of commander is 16.6.9.
