### ISSUE TITLE
Compliance command doesn't work when switched to MC (from MSP)

### ISSUE THREAD

**Issue by MtlSnk** [Keeper-Security/Commander#880]
For context:
- using Windows release, v16.8.1
- logged into user with an MSP license
- MSP doesn't have the compliance addon
- MC is assigned enterprise+ license, with compliance addon

After logging into Keeper Commander, I used `switch-to-mc <ID>` and then `compliance`.

The error message:
```python
Traceback (most recent call last):
  File "keepercommander\cli.py", line 522, in loop
  File "keepercommander\cli.py", line 366, in do_command
  File "keepercommander\commands\compliance.py", line 74, in execute_args
  File "keepercommander\commands\base.py", line 441, in execute_args
  File "keepercommander\commands\compliance.py", line 77, in validate
  File "keepercommander\sox\__init__.py", line 21, in validate_data_access
  File "keepercommander\sox\__init__.py", line 42, in is_compliance_reporting_enabled
StopIteration
```

The command works fine when I subbed to the compliance addon in the MSP and ran `compliance`, so it seems the issue lies with switching to an MC.

If you need further info, please let me know. Not sure what else to provide. :)

**Comment by sk-keeper** [comment]
Thank you for reporting this issue. It's been fixed in the `release` branch.
Commander's binaries can be downloaded from 
https://github.com/Keeper-Security/Commander/releases/tag/msp_report

**Comment by MtlSnk** [comment]
Cheers for the quick fix!
