### ISSUE TITLE
Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by jometzner** [Keeper-Security/Commander#910]
When executing `keeper search test` on a persistent login enable cli, I receive the following error instead of displaying the search result.

```
Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/home/USER/.local/lib/python3.10/site-packages/keepercommander/cli.py", line 521, in loop
    result = do_command(params, command)
  File "/home/USER/.local/lib/python3.10/site-packages/keepercommander/cli.py", line 363, in do_command
    result = command.execute_args(params, args, command=orig_cmd)
  File "/home/USER/.local/lib/python3.10/site-packages/keepercommander/commands/base.py", line 416, in execute_args
    return self.execute(params, **d)
  File "/home/USER/.local/lib/python3.10/site-packages/keepercommander/commands/record.py", line 482, in execute
    records = list(vault_extensions.find_records(params, pattern))
  File "/home/USER/.local/lib/python3.10/site-packages/keepercommander/vault_extensions.py", line 72, in find_records
    record = vault.KeeperRecord.load(params, record_uid)
  File "/home/USER/.local/lib/python3.10/site-packages/keepercommander/vault.py", line 105, in load
    extra = json.loads(record['extra_unencrypted']) if 'extra_unencrypted' in record else None
  File "/usr/lib64/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
An unexpected error occurred: Expecting value: line 1 column 1 (char 0). Type "debug" to toggle verbose error output
```

What could be the issue?

**Comment by sk-keeper** [comment]
It looks like one of your record has so called `extra` field corrupted or empty. It is expected to be a valid JSON text.
`extra` is used by the older/legacy records to store TOTP codes and file attachments.
The Commander should not crash when parsing such records. It is a bug and it will be fixed in the next Commander release.

If this broken record is found then it might be fixed in the Web Vault by editing it.
The legacy records do not have "Record Type" dropdown when edited in the Web Vault.

**Comment by jometzner** [comment]
Thank you for the insight.

Yes, I have quite a few of these old/legacy records in my account. Seems I need to tidy up a bit.

**Comment by sk-keeper** [comment]
Thank you for reporting this issue. Commander 16.8.7 now tolerates certain record corruptions.
