### ISSUE TITLE
'LastpassAttachment' object has no attribute 'prepare'

### ISSUE THREAD

**Issue by baggydog** [Keeper-Security/Commander#917]
Importing LastPass using Commander 16.8.7:

Getting revision 1282763629
Uploading v3 attachments:
'LastpassAttachment' object has no attribute 'prepare'
Traceback (most recent call last):
  File "keepercommander\cli.py", line 521, in loop
  File "keepercommander\cli.py", line 363, in do_command
  File "keepercommander\importer\commands.py", line 142, in execute_args
  File "keepercommander\commands\base.py", line 416, in execute_args
  File "keepercommander\importer\commands.py", line 210, in execute
  File "keepercommander\importer\imp_exp.py", line 920, in _import
  File "keepercommander\importer\imp_exp.py", line 1075, in upload_v3_attachments
AttributeError: 'LastpassAttachment' object has no attribute 'prepare'
An unexpected error occurred: 'LastpassAttachment' object has no attribute 'prepare'. Type "debug" to toggle verbose error output

**Comment by sk-keeper** [comment]
Thank you for reporting this issue.

It's been fixed in the Commander 16.8.8 release. Please upgrade your Commander installation.
